export const INITIALIZE = "INITIALIZE";

export const UPDATE_CORE_INFO = "UPDATE_CORE_INFO";
export const UPDATE_THEME = "UPDATE_THEME";

export const SET_AVAILABLE_MODULES = "SET_AVAILABLE_MODULES";
